version: '2'
services:

  # The Application
  app:
    image: laravel-with-docker-image
    volumes:
      - /var/www/storage
    env_file: '.env.prod'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  # The Web Server
  web:
    image: laravel-with-docker-web-image
    volumes:
      - "${LE_DIR}:/etc/letsencrypt"
    ports:
      - 80:80
      - 443:443
